export type Difficulty = "easy" | "medium" | "hard";

export type Question = {
  id: string;
  characterName: string;
  sourceTitle: string;
  category: string;
  targetPart: string;
  targetColorHex: string;
  difficulty: Difficulty;
  aliases: string[];
  regionNotes: string[];
  sourceConfidence: "manual-reviewed";
  legalUsageType: "text-reference-only";
};

export const QUESTIONS: Question[] = [
  { id: "classic-001", characterName: "SpongeBob SquarePants", sourceTitle: "SpongeBob SquarePants", category: "classic-cartoon", targetPart: "body", targetColorHex: "#F7E948", difficulty: "easy", aliases: ["spongebob yellow"], regionNotes: ["US"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-002", characterName: "Patrick Star", sourceTitle: "SpongeBob SquarePants", category: "classic-cartoon", targetPart: "skin", targetColorHex: "#F7A6B8", difficulty: "easy", aliases: ["patrick pink"], regionNotes: ["US"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-003", characterName: "Squidward", sourceTitle: "SpongeBob SquarePants", category: "classic-cartoon", targetPart: "skin", targetColorHex: "#9BC9BD", difficulty: "medium", aliases: ["squidward teal"], regionNotes: ["US"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-004", characterName: "Doraemon", sourceTitle: "Doraemon", category: "anime", targetPart: "body", targetColorHex: "#1E9FE8", difficulty: "easy", aliases: ["doraemon blue"], regionNotes: ["JP", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-005", characterName: "Nobita Nobi", sourceTitle: "Doraemon", category: "anime", targetPart: "shirt", targetColorHex: "#FFD94D", difficulty: "medium", aliases: ["nobita yellow shirt"], regionNotes: ["JP"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-006", characterName: "Pikachu", sourceTitle: "Pokémon", category: "anime", targetPart: "body", targetColorHex: "#F6D743", difficulty: "easy", aliases: ["pikachu yellow"], regionNotes: ["JP", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-007", characterName: "Pikachu", sourceTitle: "Pokémon", category: "anime", targetPart: "cheeks", targetColorHex: "#E53835", difficulty: "easy", aliases: ["pikachu red cheeks"], regionNotes: ["JP", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-008", characterName: "Homer Simpson", sourceTitle: "The Simpsons", category: "classic-cartoon", targetPart: "skin", targetColorHex: "#F7D54A", difficulty: "easy", aliases: ["simpsons yellow skin"], regionNotes: ["US"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-009", characterName: "Marge Simpson", sourceTitle: "The Simpsons", category: "classic-cartoon", targetPart: "hair", targetColorHex: "#1C6FD1", difficulty: "easy", aliases: ["marge blue hair"], regionNotes: ["US"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-010", characterName: "Bart Simpson", sourceTitle: "The Simpsons", category: "classic-cartoon", targetPart: "shirt", targetColorHex: "#F05A28", difficulty: "medium", aliases: ["bart orange shirt"], regionNotes: ["US"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-011", characterName: "Lisa Simpson", sourceTitle: "The Simpsons", category: "classic-cartoon", targetPart: "dress", targetColorHex: "#E94B35", difficulty: "medium", aliases: ["lisa red dress"], regionNotes: ["US"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-012", characterName: "Mickey Mouse", sourceTitle: "Mickey Mouse", category: "classic-cartoon", targetPart: "shorts", targetColorHex: "#E21B2D", difficulty: "easy", aliases: ["mickey red shorts"], regionNotes: ["US", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-013", characterName: "Minnie Mouse", sourceTitle: "Mickey Mouse", category: "classic-cartoon", targetPart: "bow", targetColorHex: "#E51B3E", difficulty: "easy", aliases: ["minnie red bow"], regionNotes: ["US", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-014", characterName: "Donald Duck", sourceTitle: "Donald Duck", category: "classic-cartoon", targetPart: "sailor shirt", targetColorHex: "#1B65C9", difficulty: "medium", aliases: ["donald blue shirt"], regionNotes: ["US", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-015", characterName: "Goofy", sourceTitle: "Mickey Mouse", category: "classic-cartoon", targetPart: "hat", targetColorHex: "#8AC640", difficulty: "medium", aliases: ["goofy green hat"], regionNotes: ["US", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-016", characterName: "Bugs Bunny", sourceTitle: "Looney Tunes", category: "classic-cartoon", targetPart: "fur", targetColorHex: "#9A9A9A", difficulty: "medium", aliases: ["bugs gray fur"], regionNotes: ["US"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-017", characterName: "Tweety", sourceTitle: "Looney Tunes", category: "classic-cartoon", targetPart: "feathers", targetColorHex: "#FFE44D", difficulty: "easy", aliases: ["tweety yellow"], regionNotes: ["US"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-018", characterName: "Daffy Duck", sourceTitle: "Looney Tunes", category: "classic-cartoon", targetPart: "bill", targetColorHex: "#F09A22", difficulty: "medium", aliases: ["daffy orange bill"], regionNotes: ["US"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-019", characterName: "Scooby-Doo", sourceTitle: "Scooby-Doo", category: "classic-cartoon", targetPart: "fur", targetColorHex: "#A86432", difficulty: "easy", aliases: ["scooby brown"], regionNotes: ["US"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-020", characterName: "Shaggy Rogers", sourceTitle: "Scooby-Doo", category: "classic-cartoon", targetPart: "shirt", targetColorHex: "#6FB24A", difficulty: "easy", aliases: ["shaggy green shirt"], regionNotes: ["US"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-021", characterName: "Fred Flintstone", sourceTitle: "The Flintstones", category: "classic-cartoon", targetPart: "tunic", targetColorHex: "#F07A22", difficulty: "easy", aliases: ["fred orange tunic"], regionNotes: ["US"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-022", characterName: "Wilma Flintstone", sourceTitle: "The Flintstones", category: "classic-cartoon", targetPart: "hair", targetColorHex: "#E85D23", difficulty: "medium", aliases: ["wilma orange hair"], regionNotes: ["US"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-023", characterName: "Garfield", sourceTitle: "Garfield", category: "classic-cartoon", targetPart: "fur", targetColorHex: "#F58220", difficulty: "easy", aliases: ["garfield orange"], regionNotes: ["US"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-024", characterName: "Odie", sourceTitle: "Garfield", category: "classic-cartoon", targetPart: "fur", targetColorHex: "#FFD36B", difficulty: "medium", aliases: ["odie yellow fur"], regionNotes: ["US"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-025", characterName: "Bluey", sourceTitle: "Bluey", category: "kids-shows", targetPart: "fur", targetColorHex: "#5DA7D9", difficulty: "easy", aliases: ["bluey blue fur"], regionNotes: ["AU", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-026", characterName: "Bingo", sourceTitle: "Bluey", category: "kids-shows", targetPart: "fur", targetColorHex: "#F39A3D", difficulty: "medium", aliases: ["bingo orange fur"], regionNotes: ["AU", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-027", characterName: "Peppa Pig", sourceTitle: "Peppa Pig", category: "kids-shows", targetPart: "dress", targetColorHex: "#E94A70", difficulty: "easy", aliases: ["peppa red dress"], regionNotes: ["UK", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-028", characterName: "George Pig", sourceTitle: "Peppa Pig", category: "kids-shows", targetPart: "shirt", targetColorHex: "#2DAAE1", difficulty: "easy", aliases: ["george blue shirt"], regionNotes: ["UK", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-029", characterName: "Aang", sourceTitle: "Avatar: The Last Airbender", category: "anime-inspired", targetPart: "arrow tattoo", targetColorHex: "#5DADE2", difficulty: "medium", aliases: ["aang blue arrow"], regionNotes: ["US"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-030", characterName: "Katara", sourceTitle: "Avatar: The Last Airbender", category: "anime-inspired", targetPart: "water tribe outfit", targetColorHex: "#2F80C1", difficulty: "medium", aliases: ["katara blue outfit"], regionNotes: ["US"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-031", characterName: "Naruto Uzumaki", sourceTitle: "Naruto", category: "anime", targetPart: "jacket", targetColorHex: "#F58220", difficulty: "easy", aliases: ["naruto orange jacket"], regionNotes: ["JP", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-032", characterName: "Sailor Moon", sourceTitle: "Sailor Moon", category: "anime", targetPart: "bow", targetColorHex: "#E5233F", difficulty: "medium", aliases: ["sailor moon red bow"], regionNotes: ["JP", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-033", characterName: "Goku", sourceTitle: "Dragon Ball", category: "anime", targetPart: "gi", targetColorHex: "#F47B20", difficulty: "easy", aliases: ["goku orange gi"], regionNotes: ["JP", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-034", characterName: "Vegeta", sourceTitle: "Dragon Ball", category: "anime", targetPart: "battle suit", targetColorHex: "#1F4AA8", difficulty: "medium", aliases: ["vegeta blue suit"], regionNotes: ["JP", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-035", characterName: "Mario", sourceTitle: "Super Mario", category: "video-games", targetPart: "hat", targetColorHex: "#E52521", difficulty: "easy", aliases: ["mario red hat"], regionNotes: ["JP", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-036", characterName: "Luigi", sourceTitle: "Super Mario", category: "video-games", targetPart: "hat", targetColorHex: "#2AA84A", difficulty: "easy", aliases: ["luigi green hat"], regionNotes: ["JP", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-037", characterName: "Sonic", sourceTitle: "Sonic the Hedgehog", category: "video-games", targetPart: "fur", targetColorHex: "#1E5BD8", difficulty: "easy", aliases: ["sonic blue"], regionNotes: ["JP", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-038", characterName: "Tails", sourceTitle: "Sonic the Hedgehog", category: "video-games", targetPart: "fur", targetColorHex: "#F4A12A", difficulty: "medium", aliases: ["tails orange fur"], regionNotes: ["JP", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-039", characterName: "Kirby", sourceTitle: "Kirby", category: "video-games", targetPart: "body", targetColorHex: "#F5A3C7", difficulty: "easy", aliases: ["kirby pink"], regionNotes: ["JP", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-040", characterName: "Yoshi", sourceTitle: "Super Mario", category: "video-games", targetPart: "body", targetColorHex: "#55B947", difficulty: "easy", aliases: ["yoshi green"], regionNotes: ["JP", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-041", characterName: "Spider-Man", sourceTitle: "Spider-Man", category: "superheroes", targetPart: "mask", targetColorHex: "#D9292F", difficulty: "easy", aliases: ["spiderman red mask"], regionNotes: ["US", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-042", characterName: "Batman", sourceTitle: "Batman", category: "superheroes", targetPart: "cape", targetColorHex: "#1F2937", difficulty: "medium", aliases: ["batman dark cape"], regionNotes: ["US", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-043", characterName: "Superman", sourceTitle: "Superman", category: "superheroes", targetPart: "cape", targetColorHex: "#D92332", difficulty: "easy", aliases: ["superman red cape"], regionNotes: ["US", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-044", characterName: "Wonder Woman", sourceTitle: "Wonder Woman", category: "superheroes", targetPart: "tiara", targetColorHex: "#F3C13A", difficulty: "medium", aliases: ["wonder woman gold tiara"], regionNotes: ["US", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-045", characterName: "Hulk", sourceTitle: "Hulk", category: "superheroes", targetPart: "skin", targetColorHex: "#4CAF50", difficulty: "easy", aliases: ["hulk green skin"], regionNotes: ["US", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-046", characterName: "Iron Man", sourceTitle: "Iron Man", category: "superheroes", targetPart: "armor", targetColorHex: "#B31B1B", difficulty: "medium", aliases: ["iron man red armor"], regionNotes: ["US", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-047", characterName: "Elsa", sourceTitle: "Frozen", category: "movies", targetPart: "dress", targetColorHex: "#8FD3E8", difficulty: "medium", aliases: ["elsa blue dress"], regionNotes: ["US", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-048", characterName: "Shrek", sourceTitle: "Shrek", category: "movies", targetPart: "skin", targetColorHex: "#8AA84F", difficulty: "easy", aliases: ["shrek green skin"], regionNotes: ["US", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-049", characterName: "Po", sourceTitle: "Kung Fu Panda", category: "movies", targetPart: "shorts", targetColorHex: "#B5402A", difficulty: "hard", aliases: ["po red shorts"], regionNotes: ["US", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-050", characterName: "Winnie the Pooh", sourceTitle: "Winnie the Pooh", category: "classic-cartoon", targetPart: "shirt", targetColorHex: "#D71920", difficulty: "easy", aliases: ["pooh red shirt"], regionNotes: ["US", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-051", characterName: "Tigger", sourceTitle: "Winnie the Pooh", category: "classic-cartoon", targetPart: "fur", targetColorHex: "#F28C28", difficulty: "easy", aliases: ["tigger orange fur"], regionNotes: ["US", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-052", characterName: "Hello Kitty", sourceTitle: "Hello Kitty", category: "mascots", targetPart: "bow", targetColorHex: "#E31B3F", difficulty: "easy", aliases: ["hello kitty red bow"], regionNotes: ["JP", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-053", characterName: "Keroppi", sourceTitle: "Sanrio", category: "mascots", targetPart: "skin", targetColorHex: "#61B846", difficulty: "medium", aliases: ["keroppi green"], regionNotes: ["JP", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-054", characterName: "Totoro", sourceTitle: "My Neighbor Totoro", category: "anime", targetPart: "fur", targetColorHex: "#8B8D8E", difficulty: "medium", aliases: ["totoro gray fur"], regionNotes: ["JP", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-055", characterName: "Stitch", sourceTitle: "Lilo & Stitch", category: "movies", targetPart: "fur", targetColorHex: "#3A78C2", difficulty: "easy", aliases: ["stitch blue fur"], regionNotes: ["US", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-056", characterName: "Mike Wazowski", sourceTitle: "Monsters, Inc.", category: "movies", targetPart: "skin", targetColorHex: "#8BC34A", difficulty: "easy", aliases: ["mike green skin"], regionNotes: ["US", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-057", characterName: "Sully", sourceTitle: "Monsters, Inc.", category: "movies", targetPart: "fur", targetColorHex: "#4AA3C7", difficulty: "medium", aliases: ["sully blue fur"], regionNotes: ["US", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-058", characterName: "Lightning McQueen", sourceTitle: "Cars", category: "movies", targetPart: "body", targetColorHex: "#C9151B", difficulty: "easy", aliases: ["mcqueen red body"], regionNotes: ["US", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-059", characterName: "Bob the Builder", sourceTitle: "Bob the Builder", category: "kids-shows", targetPart: "helmet", targetColorHex: "#FFD23C", difficulty: "medium", aliases: ["bob yellow helmet"], regionNotes: ["UK", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" },
  { id: "classic-060", characterName: "Dora the Explorer", sourceTitle: "Dora the Explorer", category: "kids-shows", targetPart: "shirt", targetColorHex: "#F27BB4", difficulty: "medium", aliases: ["dora pink shirt"], regionNotes: ["US", "Global"], sourceConfidence: "manual-reviewed", legalUsageType: "text-reference-only" }
];
